
# Code generated by the Assistant.

from flask import Flask, render_template, request, redirect, url_for
from coiffeur_jass_score_calculator import calculate_score

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/calculate-score', methods=['POST'])
def calculate_score_view():
    scores = [int(score) for score in request.form.getlist('score')]
    result = calculate_score(scores)
    return render_template('results.html', result=result)

@app.route('/new-game')
def new_game():
    return redirect(url_for('index'))

if __name__ == '__main__':
    app.run(debug=True)
